-- RESET DO BANCO
DROP TABLE IF EXISTS fato_desempenho;
DROP TABLE IF EXISTS dim_aluno;
DROP TABLE IF EXISTS dim_curso;
DROP TABLE IF EXISTS matricula;
DROP TABLE IF EXISTS aluno;
DROP TABLE IF EXISTS curso;
